---
include:

# gamebad mk2
- board: xiao_ble
  shield: gamebad_mk2
- board: xiao_ble
  shield: settings_reset

# gamebad mk3
- board: nice_nano
  shield: gamebad_mk3
- board: nice_nano
  shield: settings_reset
